/**
 * Canonical runtime error-code values.
 */

export const ERROR_CODES = {
  UNKNOWN: "UNKNOWN",
  NETWORK: "NETWORK_ERROR",
  TIMEOUT: "TIMEOUT",
  VALIDATION: "VALIDATION_ERROR",
  AUTHENTICATION: "AUTHENTICATION_ERROR",
  AUTHORIZATION: "AUTHORIZATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  SERVER: "SERVER_ERROR",
  TENANT: "TENANT_ERROR",
  BRANCH: "BRANCH_ERROR",
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
