"""finance checkpoint 1 customer contacts and finance profile

Revision ID: 188a2e688fa0
Revises: c2f7a9d4e1b6
Create Date: 2026-10-03 12:29:53.576246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188a2e688fa0'
down_revision = 'c2f7a9d4e1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_contacts',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_billing_contact', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contacts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_customer_contacts_tenant_active', ['tenant_id', 'is_active'], unique=False)
        batch_op.create_index('ix_customer_contacts_tenant_customer', ['tenant_id', 'customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_contacts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_customer_contacts_primary', ['customer_id'], unique=True, postgresql_where=sa.text('is_primary = true AND is_active = true'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('payment_terms_days', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('tax_identifier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('credit_hold', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.alter_column('credit_limit', server_default=None)
        batch_op.alter_column('payment_terms_days', server_default=None)
        batch_op.alter_column('credit_hold', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('credit_hold')
        batch_op.drop_column('tax_identifier')
        batch_op.drop_column('currency')
        batch_op.drop_column('payment_terms_days')
        batch_op.drop_column('credit_limit')

    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_index('uq_customer_contacts_primary', postgresql_where=sa.text('is_primary = true AND is_active = true'))
        batch_op.drop_index(batch_op.f('ix_customer_contacts_tenant_id'))
        batch_op.drop_index('ix_customer_contacts_tenant_customer')
        batch_op.drop_index('ix_customer_contacts_tenant_active')
        batch_op.drop_index(batch_op.f('ix_customer_contacts_customer_id'))

    op.drop_table('customer_contacts')
    # ### end Alembic commands ###
