"""Initial schema

Revision ID: 19b1ccd035ac
Revises: 
Create Date: 2026-07-10 17:00:31.173606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b1ccd035ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_module_code'), ['module_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('till_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('till_id', sa.UUID(), nullable=False),
    sa.Column('cashier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opening_float', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('till_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_till_shifts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_till_shifts_cashier_id'), ['cashier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_till_shifts_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_till_shifts_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_till_shifts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_till_shifts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_till_shifts_till_id'), ['till_id'], unique=False)

    op.create_table('branches',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county_state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_head_office', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_branches_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_branches_tenant_name')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('brands',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_brands_tenant_name')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customers',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('other_names', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('loyalty_points', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_number', name='uq_customers_tenant_customer_number')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('method_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_payment_methods_tenant_code')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('product_categories',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_product_categories_tenant_name')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('roles',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_roles_tenant_code')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('units_of_measure',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_factor', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_units_tenant_code')
    )
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_of_measure_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('products',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('internal_sku', sa.String(length=60), nullable=False),
    sa.Column('supplier_sku', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('track_batches', sa.Boolean(), nullable=False),
    sa.Column('track_expiry', sa.Boolean(), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('allow_negative_stock', sa.Boolean(), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('min_sale_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('default_sale_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_code', sa.String(length=30), nullable=True),
    sa.Column('pack_size', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'internal_sku', name='uq_products_tenant_internal_sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_unit_id'), ['unit_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tills',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'code', name='uq_tills_tenant_branch_code')
    )
    with op.batch_alter_table('tills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tills_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tills_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_users_tenant_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('warehouses',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('warehouse_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'code', name='uq_warehouses_tenant_branch_code')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('inventory_batches',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_batches_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('product_codes',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('code_value', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('generated_by_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code_value', name='uq_product_codes_tenant_code_value')
    )
    with op.batch_alter_table('product_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_codes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_codes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('shifts',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('till_id', sa.String(length=36), nullable=False),
    sa.Column('opened_by', sa.String(length=36), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opening_float', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_cash_expected', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closing_cash_counted', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['till_id'], ['tills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_till_id'), ['till_id'], unique=False)

    op.create_table('stock_balances',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'warehouse_id', 'product_id', name='uq_stock_balances_tenant_warehouse_product')
    )
    with op.batch_alter_table('stock_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_balances_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_balances_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_balances_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_balances_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('inventory_movements',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('sales',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('till_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('sale_number', sa.String(length=50), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sale_channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cashier_id', sa.String(length=36), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('refund_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['till_id'], ['tills.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sale_number', name='uq_sales_tenant_sale_number')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_cashier_id'), ['cashier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_sale_date'), ['sale_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_till_id'), ['till_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('sale_action_requests',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('rejected_by', sa.String(length=36), nullable=True),
    sa.Column('request_reason', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_action_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_action_requests_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_action_requests_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_action_requests_rejected_by'), ['rejected_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_action_requests_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_action_requests_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_action_requests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sale_items',
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_of_sale', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_returned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_items_sale_id'), ['sale_id'], unique=False)

    op.create_table('sale_payments',
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('payment_method_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_payments_payment_method_id'), ['payment_method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_payments_received_by'), ['received_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_payments_sale_id'), ['sale_id'], unique=False)

    op.create_table('sale_refunds',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('till_id', sa.String(length=36), nullable=False),
    sa.Column('cashier_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('refund_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('refund_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('refund_discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('refund_tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('refund_total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stock_returned', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['till_id'], ['tills.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'refund_number', name='uq_sale_refunds_tenant_refund_number')
    )
    with op.batch_alter_table('sale_refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_refunds_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refunds_cashier_id'), ['cashier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refunds_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refunds_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refunds_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refunds_till_id'), ['till_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refunds_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('sale_refund_items',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('refund_id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('sale_item_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('return_to_stock', sa.Boolean(), nullable=False),
    sa.Column('condition_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['refund_id'], ['sale_refunds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_refund_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_refund_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refund_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refund_items_refund_id'), ['refund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refund_items_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refund_items_sale_item_id'), ['sale_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_refund_items_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_refund_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_refund_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refund_items_sale_item_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refund_items_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refund_items_refund_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refund_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refund_items_batch_id'))

    op.drop_table('sale_refund_items')
    with op.batch_alter_table('sale_refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_refunds_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refunds_till_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refunds_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refunds_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refunds_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refunds_cashier_id'))
        batch_op.drop_index(batch_op.f('ix_sale_refunds_branch_id'))

    op.drop_table('sale_refunds')
    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_payments_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_payments_received_by'))
        batch_op.drop_index(batch_op.f('ix_sale_payments_payment_method_id'))

    op.drop_table('sale_payments')
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_sale_items_batch_id'))

    op.drop_table('sale_items')
    with op.batch_alter_table('sale_action_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_action_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sale_action_requests_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_action_requests_requested_by'))
        batch_op.drop_index(batch_op.f('ix_sale_action_requests_rejected_by'))
        batch_op.drop_index(batch_op.f('ix_sale_action_requests_approved_by'))
        batch_op.drop_index(batch_op.f('ix_sale_action_requests_action_type'))

    op.drop_table('sale_action_requests')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_sales_till_id'))
        batch_op.drop_index(batch_op.f('ix_sales_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sales_shift_id'))
        batch_op.drop_index(batch_op.f('ix_sales_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sales_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_cashier_id'))
        batch_op.drop_index(batch_op.f('ix_sales_branch_id'))

    op.drop_table('sales')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_reference_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_reference_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_by'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_branch_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_batch_id'))

    op.drop_table('inventory_movements')
    op.drop_table('user_roles')
    with op.batch_alter_table('stock_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_balances_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_balances_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_balances_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_balances_branch_id'))

    op.drop_table('stock_balances')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_till_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_branch_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('product_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_codes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_product_codes_product_id'))

    op.drop_table('product_codes')
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_batch_number'))

    op.drop_table('inventory_batches')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_warehouses_branch_id'))

    op.drop_table('warehouses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_branch_id'))

    op.drop_table('users')
    with op.batch_alter_table('tills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tills_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tills_branch_id'))

    op.drop_table('tills')
    op.drop_table('role_permissions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_unit_id'))
        batch_op.drop_index(batch_op.f('ix_products_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand_id'))

    op.drop_table('products')
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_of_measure_tenant_id'))

    op.drop_table('units_of_measure')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_tenant_id'))

    op.drop_table('roles')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_tenant_id'))

    op.drop_table('product_categories')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_tenant_id'))

    op.drop_table('payment_methods')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_tenant_id'))

    op.drop_table('brands')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_tenant_id'))

    op.drop_table('branches')
    with op.batch_alter_table('till_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_till_shifts_till_id'))
        batch_op.drop_index(batch_op.f('ix_till_shifts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_till_shifts_status'))
        batch_op.drop_index(batch_op.f('ix_till_shifts_opened_at'))
        batch_op.drop_index(batch_op.f('ix_till_shifts_closed_at'))
        batch_op.drop_index(batch_op.f('ix_till_shifts_cashier_id'))
        batch_op.drop_index(batch_op.f('ix_till_shifts_branch_id'))

    op.drop_table('till_shifts')
    op.drop_table('tenants')
    op.drop_table('permissions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_module_code'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_branch_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
