"""add tenant business code tax codes and number sequences

Revision ID: 1a8cd74cbf85
Revises: a890db1a5691
Create Date: 2026-08-19 21:10:04.802346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8cd74cbf85'
down_revision = 'a890db1a5691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_sequences',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=50), nullable=False),
    sa.Column('next_value', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'namespace', name='uq_number_sequences_tenant_namespace')
    )
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_number_sequences_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tax_codes',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tax_codes_tenant_code')
    )
    with op.batch_alter_table('tax_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_codes_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_tenants_business_code'), ['business_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_business_code'))
        batch_op.drop_column('business_code')

    with op.batch_alter_table('tax_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_codes_tenant_id'))

    op.drop_table('tax_codes')
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_number_sequences_tenant_id'))

    op.drop_table('number_sequences')
    # ### end Alembic commands ###
