"""add goods receipt reconciliation workflow foundation

Revision ID: 5675b38da92a
Revises: 733b2146056d
Create Date: 2026-09-07 19:06:06.318712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5675b38da92a'
down_revision = '733b2146056d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods_receipt_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoiced_quantity', sa.Numeric(precision=18, scale=4), nullable=True))
        batch_op.add_column(sa.Column('received_quantity', sa.Numeric(precision=18, scale=4), nullable=True))
        batch_op.add_column(sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=4), nullable=True))
        batch_op.add_column(sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=4), nullable=True))
        batch_op.add_column(sa.Column('bonus_quantity', sa.Numeric(precision=18, scale=4), nullable=True))
        batch_op.add_column(sa.Column('supplier_item_code', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('supplier_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('supplier_unit_price', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_percent', sa.Numeric(precision=9, scale=4), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=9, scale=4), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('net_unit_cost', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discrepancy_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('discrepancy_reason', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_goods_receipt_items_discrepancy_status'), ['discrepancy_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_items_supplier_item_code'), ['supplier_item_code'], unique=False)

    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_invoice_number', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('supplier_invoice_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('payment_terms', sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column(
                'invoice_currency',
                sa.String(length=3),
                nullable=False,
                server_default='KES',
            )
        )
        batch_op.add_column(sa.Column('supplier_subtotal', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('supplier_discount_total', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('supplier_tax_total', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('supplier_invoice_total', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('calculated_subtotal', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('calculated_tax_total', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('calculated_total', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reconciliation_difference', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('posted_by', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_goods_receipts_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_posted_by'), ['posted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_supplier_invoice_date'), ['supplier_invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_supplier_invoice_number'), ['supplier_invoice_number'], unique=False)
        batch_op.create_foreign_key(
            'fk_goods_receipts_approved_by_users',
            'users',
            ['approved_by'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_goods_receipts_posted_by_users',
            'users',
            ['posted_by'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_goods_receipts_posted_by_users',
            type_='foreignkey',
        )
        batch_op.drop_constraint(
            'fk_goods_receipts_approved_by_users',
            type_='foreignkey',
        )
        batch_op.drop_index(batch_op.f('ix_goods_receipts_supplier_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_supplier_invoice_date'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_posted_by'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_posted_at'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_approved_by'))
        batch_op.drop_column('posted_by')
        batch_op.drop_column('posted_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('reconciliation_difference')
        batch_op.drop_column('calculated_total')
        batch_op.drop_column('calculated_tax_total')
        batch_op.drop_column('calculated_subtotal')
        batch_op.drop_column('supplier_invoice_total')
        batch_op.drop_column('supplier_tax_total')
        batch_op.drop_column('supplier_discount_total')
        batch_op.drop_column('supplier_subtotal')
        batch_op.drop_column('invoice_currency')
        batch_op.drop_column('payment_terms')
        batch_op.drop_column('supplier_invoice_date')
        batch_op.drop_column('supplier_invoice_number')

    with op.batch_alter_table('goods_receipt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_items_supplier_item_code'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_items_discrepancy_status'))
        batch_op.drop_column('discrepancy_reason')
        batch_op.drop_column('discrepancy_status')
        batch_op.drop_column('line_total')
        batch_op.drop_column('net_unit_cost')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_percent')
        batch_op.drop_column('supplier_unit_price')
        batch_op.drop_column('supplier_description')
        batch_op.drop_column('supplier_item_code')
        batch_op.drop_column('bonus_quantity')
        batch_op.drop_column('rejected_quantity')
        batch_op.drop_column('accepted_quantity')
        batch_op.drop_column('received_quantity')
        batch_op.drop_column('invoiced_quantity')

    # ### end Alembic commands ###
