"""add platform iam foundation

Revision ID: 63a0122e4a04
Revises: ecda314fd79c
Create Date: 2026-09-04 20:24:45.352724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a0122e4a04'
down_revision = 'ecda314fd79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_permissions',
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_platform_permissions_module_code'), ['module_code'], unique=False)

    op.create_table('platform_roles',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_platform_roles_is_system'), ['is_system'], unique=False)

    op.create_table('platform_users',
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_platform_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_users_username'), ['username'], unique=True)

    op.create_table('platform_role_permissions',
    sa.Column('platform_role_id', sa.String(length=36), nullable=False),
    sa.Column('platform_permission_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_platform_user_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_platform_user_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['platform_permission_id'], ['platform_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_role_id'], ['platform_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('platform_role_id', 'platform_permission_id')
    )
    with op.batch_alter_table('platform_role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_role_permissions_assigned_by_platform_user_id'), ['assigned_by_platform_user_id'], unique=False)
        batch_op.create_index('ix_platform_role_permissions_permission', ['platform_permission_id'], unique=False)
        batch_op.create_index('ix_platform_role_permissions_role', ['platform_role_id'], unique=False)

    op.create_table('platform_user_roles',
    sa.Column('platform_user_id', sa.String(length=36), nullable=False),
    sa.Column('platform_role_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_platform_user_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_platform_user_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['platform_role_id'], ['platform_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('platform_user_id', 'platform_role_id')
    )
    with op.batch_alter_table('platform_user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_user_roles_assigned_by_platform_user_id'), ['assigned_by_platform_user_id'], unique=False)
        batch_op.create_index('ix_platform_user_roles_role', ['platform_role_id'], unique=False)
        batch_op.create_index('ix_platform_user_roles_user', ['platform_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_user_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_platform_user_roles_user')
        batch_op.drop_index('ix_platform_user_roles_role')
        batch_op.drop_index(batch_op.f('ix_platform_user_roles_assigned_by_platform_user_id'))

    op.drop_table('platform_user_roles')
    with op.batch_alter_table('platform_role_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_platform_role_permissions_role')
        batch_op.drop_index('ix_platform_role_permissions_permission')
        batch_op.drop_index(batch_op.f('ix_platform_role_permissions_assigned_by_platform_user_id'))

    op.drop_table('platform_role_permissions')
    with op.batch_alter_table('platform_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_users_username'))
        batch_op.drop_index(batch_op.f('ix_platform_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_platform_users_email'))

    op.drop_table('platform_users')
    with op.batch_alter_table('platform_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_roles_is_system'))
        batch_op.drop_index(batch_op.f('ix_platform_roles_code'))

    op.drop_table('platform_roles')
    with op.batch_alter_table('platform_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_permissions_module_code'))
        batch_op.drop_index(batch_op.f('ix_platform_permissions_code'))

    op.drop_table('platform_permissions')
    # ### end Alembic commands ###
