"""add platform authentication persistence

Revision ID: 733b2146056d
Revises: 63a0122e4a04
Create Date: 2026-09-04 21:45:05.514294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '733b2146056d'
down_revision = '63a0122e4a04'
branch_labels = None
depends_on = None

token_revocation_reason_enum = postgresql.ENUM(
    "LOGOUT",
    "LOGOUT_ALL",
    "TOKEN_ROTATED",
    "PASSWORD_CHANGED",
    "ACCOUNT_DISABLED",
    "ADMIN_REVOKED",
    "SESSION_TAKEOVER",
    "REUSE_DETECTED",
    "SECURITY_EVENT",
    "SESSION_EXPIRED",
    "USER_DELETED",
    name="tokenrevocationreason",
    create_type=False,
)


def upgrade():
    bind = op.get_bind()

    token_revocation_reason_enum.create(
        bind,
        checkfirst=True,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_login_attempts',
    sa.Column('platform_user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_platform_login_attempts_created', ['created_at'], unique=False)
        batch_op.create_index('ix_platform_login_attempts_email', ['email'], unique=False)
        batch_op.create_index('ix_platform_login_attempts_email_created', ['email', 'created_at'], unique=False)
        batch_op.create_index('ix_platform_login_attempts_email_success_created', ['email', 'successful', 'created_at'], unique=False)
        batch_op.create_index('ix_platform_login_attempts_ip', ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_login_attempts_platform_user_id'), ['platform_user_id'], unique=False)
        batch_op.create_index('ix_platform_login_attempts_successful', ['successful'], unique=False)

    op.create_table('platform_sessions',
    sa.Column('platform_user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('browser', sa.String(length=150), nullable=True),
    sa.Column('operating_system', sa.String(length=150), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('last_ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('authentication_method', sa.String(length=50), nullable=True),
    sa.Column('authentication_level', sa.String(length=50), nullable=True),
    sa.Column('mfa_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_platform_user_id', sa.String(length=36), nullable=True),
    sa.Column('revoke_reason', token_revocation_reason_enum, nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_platform_sessions_expiry'),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_platform_user_id'], ['platform_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_platform_sessions_active', ['revoked_at', 'expires_at'], unique=False)
        batch_op.create_index('ix_platform_sessions_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_platform_sessions_fingerprint', ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_sessions_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_sessions_revoked_by_platform_user_id'), ['revoked_by_platform_user_id'], unique=False)
        batch_op.create_index('ix_platform_sessions_user', ['platform_user_id'], unique=False)

    op.create_table('platform_refresh_tokens',
    sa.Column('platform_user_id', sa.String(length=36), nullable=False),
    sa.Column('platform_session_id', sa.String(length=36), nullable=False),
    sa.Column('jwt_id', sa.String(length=64), nullable=False),
    sa.Column('token_family', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_token_id', sa.String(length=36), nullable=True),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('last_ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_platform_user_id', sa.String(length=36), nullable=True),
    sa.Column('revoke_reason', token_revocation_reason_enum, nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_platform_refresh_tokens_expiry'),
    sa.ForeignKeyConstraint(['parent_token_id'], ['platform_refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_session_id'], ['platform_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_platform_user_id'], ['platform_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jwt_id', name='uq_platform_refresh_tokens_jti')
    )
    with op.batch_alter_table('platform_refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_platform_refresh_tokens_active', ['revoked_at', 'expires_at'], unique=False)
        batch_op.create_index('ix_platform_refresh_tokens_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_platform_refresh_tokens_family', ['token_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_refresh_tokens_last_used_at'), ['last_used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_refresh_tokens_parent_token_id'), ['parent_token_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_refresh_tokens_replaced_at'), ['replaced_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_refresh_tokens_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_refresh_tokens_revoked_by_platform_user_id'), ['revoked_by_platform_user_id'], unique=False)
        batch_op.create_index('ix_platform_refresh_tokens_session', ['platform_session_id'], unique=False)
        batch_op.create_index('ix_platform_refresh_tokens_user', ['platform_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_platform_refresh_tokens_user')
        batch_op.drop_index('ix_platform_refresh_tokens_session')
        batch_op.drop_index(batch_op.f('ix_platform_refresh_tokens_revoked_by_platform_user_id'))
        batch_op.drop_index(batch_op.f('ix_platform_refresh_tokens_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_platform_refresh_tokens_replaced_at'))
        batch_op.drop_index(batch_op.f('ix_platform_refresh_tokens_parent_token_id'))
        batch_op.drop_index(batch_op.f('ix_platform_refresh_tokens_last_used_at'))
        batch_op.drop_index('ix_platform_refresh_tokens_family')
        batch_op.drop_index('ix_platform_refresh_tokens_expires')
        batch_op.drop_index('ix_platform_refresh_tokens_active')

    op.drop_table('platform_refresh_tokens')
    with op.batch_alter_table('platform_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_platform_sessions_user')
        batch_op.drop_index(batch_op.f('ix_platform_sessions_revoked_by_platform_user_id'))
        batch_op.drop_index(batch_op.f('ix_platform_sessions_revoked_at'))
        batch_op.drop_index('ix_platform_sessions_fingerprint')
        batch_op.drop_index('ix_platform_sessions_expires')
        batch_op.drop_index('ix_platform_sessions_active')

    op.drop_table('platform_sessions')
    with op.batch_alter_table('platform_login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_platform_login_attempts_successful')
        batch_op.drop_index(batch_op.f('ix_platform_login_attempts_platform_user_id'))
        batch_op.drop_index('ix_platform_login_attempts_ip')
        batch_op.drop_index('ix_platform_login_attempts_email_success_created')
        batch_op.drop_index('ix_platform_login_attempts_email_created')
        batch_op.drop_index('ix_platform_login_attempts_email')
        batch_op.drop_index('ix_platform_login_attempts_created')

    op.drop_table('platform_login_attempts')

    bind = op.get_bind()

    token_revocation_reason_enum.drop(
        bind,
        checkfirst=True,
    )

    # ### end Alembic commands ###
