"""allow platform audit events without tenant

Revision ID: 7e7141e792bb
Revises: ade87739755f
Create Date: 2026-08-16 21:58:36.768429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7141e792bb'
down_revision = 'ade87739755f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
