"""add tenant workspace slug

Revision ID: a6c3b26915df
Revises: 1a8cd74cbf85
Create Date: 2026-08-20 19:04:22.087940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c3b26915df'
down_revision = '1a8cd74cbf85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_slug', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_tenants_workspace_slug'), ['workspace_slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_workspace_slug'))
        batch_op.drop_column('workspace_slug')

    # ### end Alembic commands ###
