"""add user permission overrides

Revision ID: c546daa8819b
Revises: 7e7141e792bb
Create Date: 2026-08-17 18:18:04.482015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c546daa8819b'
down_revision = '7e7141e792bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('effect', sa.String(length=10), nullable=False),
    sa.Column('assigned_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("effect IN ('allow', 'deny')", name='ck_user_permissions_effect'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.create_index('ix_user_permissions_permission', ['permission_id'], unique=False)
        batch_op.create_index('ix_user_permissions_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_permissions_user')
        batch_op.drop_index('ix_user_permissions_permission')

    op.drop_table('user_permissions')
    # ### end Alembic commands ###
