"""finance checkpoint 2 chart of accounts

Revision ID: ddd36b184c40
Revises: 188a2e688fa0
Create Date: 2026-10-06 22:15:23.439469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd36b184c40'
down_revision = '188a2e688fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('account_code', sa.String(length=30), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_account', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_type IN ('asset', 'liability', 'equity', 'revenue', 'expense')", name='ck_chart_of_accounts_account_type'),
    sa.CheckConstraint("normal_balance IN ('debit', 'credit')", name='ck_chart_of_accounts_normal_balance'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name='ck_chart_of_accounts_not_self_parent'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_code', name='uq_chart_of_accounts_tenant_code')
    )
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_is_system_account'), ['is_system_account'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index('ix_chart_of_accounts_tenant_branch', ['tenant_id', 'branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_chart_of_accounts_tenant_parent', ['tenant_id', 'parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_chart_of_accounts_tenant_parent')
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_tenant_id'))
        batch_op.drop_index('ix_chart_of_accounts_tenant_branch')
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_parent_id'))
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_is_system_account'))
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_is_active'))
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_branch_id'))

    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
