/**
 * ============================================================================
 * Hela360 Enterprise Goods Receipt Service
 * ============================================================================
 *
 * Service responsible for Goods Receipt Note (GRN) management.
 *
 * Responsibilities
 * ----------------
 * • Goods receipt CRUD
 * • Receive purchase orders
 * • Partial receiving
 * • Batch creation
 * • Expiry tracking
 * • Inventory posting
 * • Receiving history
 * • Receiving documents
 * • Receiving validation
 * • Receiving reversal
 *
 * Goods Receipts bridge Procurement and Inventory. Every received item
 * ultimately results in inventory stock movements.
 *
 * ============================================================================
 */

import type { AxiosRequestConfig } from "axios";

import { API_ENDPOINTS } from "@/api/endpoints";

import BaseService from "@/services/base";

import type { ApiResponse } from "@/types/api";

/* ============================================================================
 * Types
 * ============================================================================
 */

export type GoodsReceiptStatus =
  | "DRAFT"
  | "POSTED"
  | "CANCELLED";

export interface GoodsReceiptItem {
  id: string;

  purchaseOrderItemId: string;

  productId: string;

  sku: string;

  productName: string;

  batchNumber: string;

  expiryDate?: string;

  quantityReceived: number;

  unitCost: number;

  lineTotal: number;
}

export interface GoodsReceipt {
  id: string;

  receiptNumber: string;

  purchaseOrderId: string;

  supplierId: string;

  supplierName: string;

  receivedDate: string;

  receivedBy: string;

  status: GoodsReceiptStatus;

  remarks?: string;

  items: GoodsReceiptItem[];

  createdAt: string;

  updatedAt: string;
}

export interface CreateGoodsReceiptRequest {
  purchaseOrderId: string;

  receivedDate?: string;

  remarks?: string;

  items: {
    purchaseOrderItemId: string;

    quantityReceived: number;

    batchNumber: string;

    expiryDate?: string;

    unitCost: number;
  }[];
}

export interface ReverseReceiptRequest {
  reason: string;
}

export interface ReceiptSummary {
  totalItems: number;

  totalQuantity: number;

  totalValue: number;
}

/* ============================================================================
 * Goods Receipt Service
 * ============================================================================
 */

export class GoodsReceiptService extends BaseService<
  GoodsReceipt,
  CreateGoodsReceiptRequest
> {
  constructor() {
    super(API_ENDPOINTS.GOODS_RECEIPTS.ROOT);
  }

  /* ==========================================================================
   * Purchase Orders
   * ==========================================================================
   */

  /**
   * Returns the purchase order associated with this receipt.
   */
  async purchaseOrder(
    receiptId: string,
    config?: AxiosRequestConfig,
  ): Promise<ApiResponse<unknown>> {
    const response =
      await this.getRequest<ApiResponse<unknown>>(
        `${this.resource}/${receiptId}/purchase-order`,
        config,
      );

    return response.data;
  }

  /* ==========================================================================
   * Inventory
   * ==========================================================================
   */

  /**
   * Posts inventory movements generated by this receipt.
   */
  async post(
    receiptId: string,
    config?: AxiosRequestConfig,
  ): Promise<ApiResponse<void>> {
    const response =
      await this.postRequest<ApiResponse<void>>(
        `${this.resource}/${receiptId}/post`,
        undefined,
        config,
      );

    return response.data;
  }

  /**
   * Reverse a posted receipt.
   */
  async reverse(
    receiptId: string,
    payload: ReverseReceiptRequest,
    config?: AxiosRequestConfig,
  ): Promise<ApiResponse<void>> {
    const response =
      await this.postRequest<ApiResponse<void>>(
        `${this.resource}/${receiptId}/reverse`,
        payload,
        config,
      );

    return response.data;
  }

  /* ==========================================================================
   * Summary
   * ==========================================================================
   */

  /**
   * Returns receipt totals.
   */
  async summary(
    receiptId: string,
    config?: AxiosRequestConfig,
  ): Promise<ApiResponse<ReceiptSummary>> {
    const response =
      await this.getRequest<ApiResponse<ReceiptSummary>>(
        `${this.resource}/${receiptId}/summary`,
        config,
      );

    return response.data;
  }

  /* ==========================================================================
   * Batches
   * ==========================================================================
   */

  /**
   * Returns batches created by this receipt.
   */
  async batches(
    receiptId: string,
    config?: AxiosRequestConfig,
  ): Promise<ApiResponse<unknown[]>> {
    const response =
      await this.getRequest<ApiResponse<unknown[]>>(
        `${this.resource}/${receiptId}/batches`,
        config,
      );

    return response.data;
  }

  /* ==========================================================================
   * Documents
   * ==========================================================================
   */

  /**
   * Print Goods Receipt Note.
   */
  async print(
    receiptId: string,
    config?: AxiosRequestConfig,
  ): Promise<Blob> {
    const response =
      await this.download(
        `${this.resource}/${receiptId}/print`,
        {
          ...config,
          responseType: "blob",
        },
      );

    return response.data;
  }

  /* ==========================================================================
   * Validation
   * ==========================================================================
   */

  /**
   * Validate a receipt before posting.
   */
  async validate(
    receiptId: string,
    config?: AxiosRequestConfig,
  ): Promise<ApiResponse<void>> {
    const response =
      await this.getRequest<ApiResponse<void>>(
        `${this.resource}/${receiptId}/validate`,
        config,
      );

    return response.data;
  }
}

/* ============================================================================
 * Singleton
 * ============================================================================
 */

export const goodsReceiptService =
  new GoodsReceiptService();

export default goodsReceiptService;