/**
 * ============================================================================
 * Hela360 Enterprise Finance Services
 * ============================================================================
 *
 * Public exports for the Finance domain.
 *
 * Responsibilities
 * ----------------
 * • Payment management
 * • Invoice management
 *
 * Financial workflows consume transactions generated by:
 *
 * • Sales
 * • Procurement
 * • Customers
 * • Suppliers
 *
 * Import finance services exclusively through this barrel file.
 *
 * Example
 * -------
 *
 * import {
 *   paymentService,
 *   invoiceService,
 * } from "@/services/finance";
 *
 * ============================================================================
 */

/* ============================================================================
 * Payments
 * ============================================================================
 */

export {
  PaymentService,
  paymentService,
} from "./paymentService";

export type {
  Payment,
  PaymentMethod,
  PaymentStatus,
  PaymentSummary,
  CreatePaymentRequest,
  UpdatePaymentRequest,
} from "./paymentService";

/* ============================================================================
 * Invoices
 * ============================================================================
 */

export {
  InvoiceService,
  invoiceService,
} from "./invoiceService";

export type {
  Invoice,
  InvoiceItem,
  InvoiceStatus,
  InvoiceSummary,
  CreateInvoiceRequest,
  UpdateInvoiceRequest,
} from "./invoiceService";